### ISSUE TITLE
Milestone 2 - functions for abstraction

### ISSUE THREAD

**Issue by mahdiheydar** [DSCI-310/DSCI-310-Group-10#38]
Questions for TA:

1. do we need a separate script for reading in data?

functions for abstraction

1. within cleaning combine eda functions info, describe, and summarization of data
2. histograms for eda **
3. train test splits **
4. ridge alpha hyperparameter optimization
5. ridge cv plot, knn plot **
6. hyperparameter tuning for k in knn classification **
7. discussion plots **

Make sure to test these functions with appropriate style guide
** functions are ones to prioritize

**Comment by nkoda** [comment]
* when refactoring the code, follow the following documentation https://py-pkgs.org/05-testing
* we should use pytest as listed in the documantation and follow the function definition styleguide.

**Comment by nkoda** [comment]
Mahdi will do discussion plots,
nikko will do the histogram EDA,
Harry will do the hyperparameter tuning
Ahmed will do the train-test split

**Comment by nkoda** [comment]
created a proper milestone for this

**Comment by nkoda** [comment]
Merged histogram plots and ridge hyperparameter abstracted functions into develop branch. Notebook now references these

**Comment by mahdiheydar** [comment]
I am almost done with tests for the plotting function. I will create a pull request when all tests are exhausted

**Comment by izk20** [comment]
merged my test and function documentation files into develop, will refactor the code in the notebook shortly

**Comment by harrysyz99** [comment]
I also write an additional function just for back up

**Comment by izk20** [comment]
Finished refactoring of split_drop.
All tests pass and all function documentation is complete. All functions refactored in notebook.
Issue resolved.
