### ISSUE TITLE
Script for downloading data off the internet

### ISSUE THREAD

**Issue by nkoda** [DSCI-310/DSCI-310-Group-10#58]
There should be a script that downloads our data from the web into a CSV.

A first script that downloads the data from the internet and saves it locally. This should take at least two arguments:

* the path to the input file (a URL or a relative local path, such as data/file.csv), as well as
* a path/filename where to write the file to and what to call it (e.g., data/cleaned_data.csv)

__Note: choose more descriptive filenames than the ones used above. These are general for illustrative purposes.__

**Comment by harrysyz99** [comment]
created the link to be used in the script, https://onedrive.live.com/download?cid=3186CCDB0C6495E0&resid=3186CCDB0C6495E0%2157273&authkey=AK4_vAlM4AFx7_M.  Might need to discuss the link/dataset situation privately with Tiffany.

**Comment by izk20** [comment]
This script has been completed (using the above link). It is called download_dataset_script.R, and downloads the dataset then saves it as a csv.
