### ISSUE TITLE
A data cleaning script

### ISSUE THREAD

**Issue by nkoda** [DSCI-310/DSCI-310-Group-10#59]
A second script that reads the data from the first script and performs and data cleaning/pre-processing, transforming, and/or partitioning that needs to happen before exploratory data analysis or modeling takes place. This should take at least two arguments:

* a path/filename pointing to the data to be read in
* a path/filename pointing to where the cleaned/processed/transformed/partitioned data should live.

**Comment by izk20** [comment]
This script has been completed, and is called read_process_script.py. It outputs the processed dataset, as well as the training and testing data to be used in the ridge regression script.

**Comment by mahdiheydar** [comment]
helped in debugging this script:
- properly formatted to docopt style guide
- typos and names fixed
- localization issues
