### ISSUE TITLE
Data Visualizations and tables

### ISSUE THREAD

**Issue by nkoda** [DSCI-310/DSCI-310-Group-10#60]
A third script which creates exploratory data visualization(s) and table(s) that are useful to help the reader/consumer understand that data set. These analysis artifacts should be written to files. This should take at least two arguments:

* a path/filename pointing to the data,
* a path/filename prefix where to write the figure to and what to call it (e.g., results/this_eda.png).

**Comment by nkoda** [comment]
It looks like that your docopt scripts aren't in proper format. Consider looking at @harrysyz99 hyperparameter script for reference.

**Comment by nkoda** [comment]
Now for why your functions arent calling properly, it looks like call to main was indented. This needs to be not indented as thats how main function is called in the script. Unindent ```if __name__ == "__main__":```

**Comment by mahdiheydar** [comment]
This has been finished. All figures were saved successfully, but the grouped data frame was done tentatively, a separate script needs to be made to make this dataframe.

**Comment by mahdiheydar** [comment]
I successfully debugged the script, it now runs with the outputs from the knn classification script. The grouped dataframe did not constitute a new script on its own, so I simply added it to this script
