### ISSUE TITLE
Modeling and Summary Script: Knn classification

### ISSUE THREAD

**Issue by izk20** [DSCI-310/DSCI-310-Group-10#63]
Create a script that reads the data from the cleaning/pre-processing script, performs the modeling and summarizes the results as a figure(s) and a table(s). These analysis artifacts should be written to files. This should take at least two arguments:

- [ ] a path/filename pointing to the data
- [ ] a path/filename prefix where to write the figure(s)/table(s) to and what to call it (e.g., results/this_analysis)

**Comment by nkoda** [comment]
It looks like the confusion matrix is recieving a  ```None``` object. Consider the following fix:
```
def create_pipeline(train1, train2, test1, test2, preprocessor):
    pipe_final = make_pipeline(preprocessor, KNeighborsClassifier(n_neighbors=26))
    pipe_final.fit(train1, train2)
    pipe_final.score(test1, test2)
    return pipe_final
```

**Comment by izk20** [comment]
This script has been completed (by implementing the above fix). It is called knn_classification_script.py, and outputs the elbow plot and confusion matrix.
