### ISSUE TITLE
Cannot start the first script

### ISSUE THREAD

**Issue by izk20** [DSCI-310/DSCI-310-Group-10#66]
I am unable to start the script to download the dataset from the internet because I don't actually have the link. I will work on the other 2 scripts in the meantime.

**Comment by harrysyz99** [comment]
working on it the nesstar shut down I am doing it n another way

**Comment by mahdiheydar** [comment]
harry make sure that the script for loading in data takes two arguments as specified on the milestone page:

A first script that downloads the data from the internet and saves it locally. This should take at least two arguments:

the path to the input file (a URL or a relative local path, such as data/file.csv), as well as
a path/filename where to write the file to and what to call it (e.g., data/cleaned_data.csv).

**Comment by harrysyz99** [comment]
case solved
