### ISSUE TITLE
files needed for visualization scripts

### ISSUE THREAD

**Issue by mahdiheydar** [DSCI-310/DSCI-310-Group-10#74]
I need the test_2 and X_test_2 dataframe objects to be saved using the pickle and let me know the filing structure

**Comment by mahdiheydar** [comment]
i need the final pipeline as well

**Comment by izk20** [comment]
All files have been saved as pickled objects and committed to knn_classification script.

**Comment by mahdiheydar** [comment]
thanks, they work with my script
